"""
email_briefing.py — Send AI/intelligence briefings via SMTP.

Required .env vars:
    EMAIL_SMTP_HOST      e.g. smtp.gmail.com
    EMAIL_SMTP_PORT      e.g. 587
    EMAIL_FROM           sender address
    EMAIL_PASSWORD       SMTP password / app password
    EMAIL_DEFAULT_TO     (optional) pre-fill recipient
"""

from __future__ import annotations

import os
import smtplib
import textwrap
from dataclasses import dataclass
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

_REPO_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(_REPO_ROOT / ".env", override=True)


@dataclass
class SMTPConfig:
    host: str
    port: int
    from_addr: str
    password: str
    default_to: str


def load_smtp_config() -> Optional[SMTPConfig]:
    # Re-read .env on every call so Streamlit's persistent process picks up changes
    load_dotenv(_REPO_ROOT / ".env", override=True)
    host = os.getenv("EMAIL_SMTP_HOST", "").strip()
    port_str = os.getenv("EMAIL_SMTP_PORT", "587").strip()
    from_addr = os.getenv("EMAIL_FROM", "").strip()
    password = os.getenv("EMAIL_PASSWORD", "").strip()
    default_to = os.getenv("EMAIL_DEFAULT_TO", "").strip()

    if not (host and from_addr and password):
        return None

    try:
        port = int(port_str)
    except ValueError:
        port = 587

    return SMTPConfig(
        host=host,
        port=port,
        from_addr=from_addr,
        password=password,
        default_to=default_to,
    )


def smtp_configured() -> bool:
    return load_smtp_config() is not None


def _markdown_to_html(md: str) -> str:
    """Minimal markdown → HTML: headers, bold, bullets. No external deps."""
    lines = []
    for line in md.splitlines():
        stripped = line.rstrip()
        if stripped.startswith("### "):
            lines.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            lines.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            lines.append(f"<h1>{stripped[2:]}</h1>")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            lines.append(f"<li>{stripped[2:]}</li>")
        elif stripped == "":
            lines.append("<br>")
        else:
            # bold
            import re

            stripped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)
            lines.append(f"<p>{stripped}</p>")
    return "\n".join(lines)


def _build_html(title: str, meta: str, briefing_md: str) -> str:
    body_html = _markdown_to_html(briefing_md)
    return textwrap.dedent(
        f"""\
        <!DOCTYPE html>
        <html>
        <head>
        <meta charset="utf-8">
        <style>
          body {{ font-family: Georgia, serif; max-width: 760px; margin: 0 auto;
                 padding: 32px 24px; color: #1a1a2e; background: #ffffff; }}
          h1 {{ font-size: 22px; color: #0d3349; border-bottom: 2px solid #1a7fb5;
                padding-bottom: 8px; margin-bottom: 4px; }}
          .meta {{ font-size: 12px; color: #666; margin-bottom: 24px; }}
          h2 {{ font-size: 17px; color: #0d3349; margin-top: 28px; margin-bottom: 6px; }}
          h3 {{ font-size: 15px; color: #1a5276; margin-top: 20px; margin-bottom: 4px; }}
          p, li {{ font-size: 14px; line-height: 1.65; color: #2c2c2c; }}
          li {{ margin-bottom: 4px; }}
          strong {{ color: #0d3349; }}
          .footer {{ margin-top: 40px; font-size: 11px; color: #999;
                     border-top: 1px solid #ddd; padding-top: 12px; }}
        </style>
        </head>
        <body>
        <h1>{title}</h1>
        <div class="meta">{meta}</div>
        {body_html}
        <div class="footer">Generated by Evidence Gap &nbsp;·&nbsp; Bold Wave Productions</div>
        </body>
        </html>
    """
    )


def _build_plain(title: str, meta: str, briefing_md: str) -> str:
    return f"{title}\n{meta}\n\n{briefing_md}\n\n---\nGenerated by Evidence Gap · Bold Wave Productions"


def send_briefing(
    to_addr: str,
    subject: str,
    title: str,
    meta: str,
    briefing_md: str,
) -> None:
    """
    Send a briefing email. Raises on any SMTP failure.
    """
    cfg = load_smtp_config()
    if cfg is None:
        raise RuntimeError(
            "EMAIL_SMTP_HOST, EMAIL_FROM, and EMAIL_PASSWORD must be set in .env"
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = cfg.from_addr
    msg["To"] = to_addr

    plain = _build_plain(title, meta, briefing_md)
    html = _build_html(title, meta, briefing_md)

    msg.attach(MIMEText(plain, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    with smtplib.SMTP(cfg.host, cfg.port, timeout=30) as server:
        server.ehlo()
        server.starttls()
        server.login(cfg.from_addr, cfg.password)
        server.sendmail(cfg.from_addr, to_addr, msg.as_string())
